index:
    path: /
    controller: App\Controller\HomepageController::index

candidat_show:
    path: /candidates
    controller: App\Controller\CandidatesController::index
    
orp_show:
    path: /orps
    controller: App\Controller\OrpsController::index
    
unemploymentFund_show:
    path: /caisseChomage
    controller: App\Controller\UnemploymentFundController::index
    
